### ISSUE TITLE
Сonnection

### ISSUE THREAD

**Issue by borisovdmitry** [cargomedia/socket-redis#60]
I'm having trouble understanding how this module is connected.I use this code, but I have a feeling that the server is not created.
var socket = require("socket-redis");
Question to the author and those who use it, could you give a detailed example?

**Comment by ssuperczynski** [comment]
Could you paste an error that you get?

**Comment by njam** [comment]
We're running socket-redis as a standalone daemon by running `node bin/socket-redis`.
If you install socket-redis with npm you'll probably have it on your `$PATH` and could just run:
```
socket-redis
```

For Debian/sysvinit here's an example init script from our puppet module: [init.sh](https://github.com/cargomedia/puppet-packages/blob/master/modules/socket_redis/templates/init.sh).

Requiring socket-redis as a library (without the binary) just gives you access to the `Server` and `Worker` class but doesn't start any server.

Does that help?

**Comment by borisovdmitry** [comment]
> Requiring socket-redis as a library (without the binary) just gives you access to the Server and Worker class but doesn't start any server.

Thank you, it's valuable. Can I ask for any minimum working example of how to create a server on the basis that returns the connection
> var socket = require ("socket-redis"); 

At this point, installation is not covered may ask about the obvious things, but I do not understand. I would be grateful for any help.

**Comment by njam** [comment]
The best example would be the one found in `[bin/socket-redis.js](https://github.com/cargomedia/socket-redis/blob/master/bin/socket-redis.js)`.

Currently the file is doing a few things:
1. Parsing command line arguments
2. Setting up logging
3. Launching worker processes (forking)

Each child process again runs `bin/socket-redis.js` but goes into the `else` part of the big `if`. So it's important that this file contains both code paths (parent and child).

Can I ask you what the reason is that you want to include socket-redis into another Node.js project's code? The main purpose (I'm using it for) is to expose a WebSocket pub/sub server over Redis. If my project was built in Node.js I could just use Sock.js or plain WebSocket.

**Comment by borisovdmitry** [comment]
Thank, look at an example.
In my project (lead development on loсalhost) is used for caching redis, want to organize a live notification does the user chose this SockJS. Javascript know well, but node.js - is very different from what used to work.

**Comment by njam** [comment]
Great to hear that it works for you!

I've added some explanation and an example how to start a server in https://github.com/cargomedia/socket-redis/pull/61
